### ISSUE TITLE
JOSS Review Comments

### ISSUE THREAD

**Issue by AoifeHughes** [snowformatics/macrobot#1]
Re: [https://github.com/openjournals/joss-reviews/issues/2259](https://github.com/openjournals/joss-reviews/issues/2259) I'll be putting review comments here. 

I'll start the full review shortly, but firstly I wanted to make you aware that some images in your readme.md are broken e.g. [https://github.com/snowformatics/GSOC/blob/master/Slide1.png](https://github.com/snowformatics/GSOC/blob/master/Slide1.png). If you could check through and fix these it'll save time during the review process. 

Thanks for the submission and I look forward to reviewing this.

**Comment by snowformatics** [comment]
Thanks, I fixed the images should be fine now...

Looking forward to your review :)

**Comment by AoifeHughes** [comment]
# Paper Comments 

I'd like to prefix these comments by saying that they are general suggestions that I, as the reader, feel would help improve readability and clarity. If they seem blunt, this is not the intent :)

- I think a reference to a review article for the first few sentences would be good. 
- Use of the word 'probably'. Personally I feel this isn't a good word to use when making a scientific point, particularly when not backed up with references. 
-  "The plant breeding is as old as the domestication ..." This sentence doesn't make sense. You could remove "The" and it would read better. 
- A more general comment would be to consider spacing out information in paragraphs. The first page is essentially a single paragraph. It may work better if you made a single paragraph introduction to pathogens being an issue and how plant breeding attempts to tackle problems then a second paragraph which states how your approach feeds into this. 
- The phrasing of "a combined term
that refers to the fields of study in biology ending in -omics," is superfluous. It could simply be "(genomics, proteomics, metabolomics etc.)"
- Again, I would consider restructuring. You talk of the breeding for 10k years, jump to omics then back to breeders not using them. It may work better if mentioned how most breeding hasn't evolved since domestication and that your method helps to bring in 21st century technology. 
- "Introduction ~~cing~~ of ~~the~~ so-called".
- Overuse of "so-called". Possibly not required at all.
- "... significantly withdrawn" I don't think this word means what you want to say. Maybe "arrested" or plainly state "Early phenotyping was held back by the difficulty in developing high-throughput pipelines for both macroscopic and microscopic data". 
- "To contribute to" -> "To solve these problems". Use of "to" twice doesn't read well. 
- The introduction of your method could be a new paragraph. It would really help the reader jump straight to reading about what you have done. As currently it is hidden amongst background information. 
- After you introduce your method you jump back to the effects of powdery mildew. As I mentioned previously, this could be part of the introduction and justification of this work. 
- Figure 1. A more detailed caption is needed. Figures should be independent of article text, so maybe a step by step caption would be useful. Currently I can guess what the figure is saying, but a detailed caption would really help. 
- Latin names for pathogens should be in italics (typically, not 100% on what JOSS' policy is).
- When you say "contains modules for" do you mean software modules? If so could you state what the changes are and how difficult would it be to say add another disease for another plant. i.e. if I wanted to do this method for rice plants is it the case of 1 week, 1 month, 1 year? If your method can be applied more widely then it would be to your benefit to state this. Possibly just a sentence on "This method was developed for mildew, with little modification it works with wheat, thus we propose that many other diseases could be applied without difficulty", just an example. 
- I'd be careful of your conclusion statements. "... Is essential to truly understand the defense mechanism", from reading this text you haven't explicitly stated how your method provides information on defence mechanisms, just that you capture data. Sorry, but this is a subtlety that I feel is important to expand upon in the text. It would give a lot more impact if you clearly state that your method is very useful because X. 
- There are a few spelling and grammar mistakes I haven't pointed out. I think copying and pasting your text into a word-processor (Libre-office or MS-word) and setting to English spellcheck would help a lot. 
- One extra thing I just noticed before hitting comment. I don't see that you've referenced your figure in the text. Maybe it would be helpful to break down also in the text what the steps for this method are i.e. what materials and steps does someone need to do if they wanted to use this method themselves. 

Again, I do hope you see that these are comments of my opinion and not always correct. I'm still going through the rest of the repository and will have more comments shortly.

**Comment by snowformatics** [comment]
**Dear Nathan. Thank you very much for your critical reading and valuable comments. Your input is
highly appreciated.**

> # Paper Comments
> I'd like to prefix these comments by saying that they are general suggestions that I, as the reader, feel would help improve readability and clarity. If they seem blunt, this is not the intent :)
> 
> * I think a reference to a review article for the first few sentences would be good.

**[Done]**
> * Use of the word 'probably'. Personally I feel this isn't a good word to use when making a scientific point, particularly when not backed up with references.

**We have rephrased the sentence and added references but, in our opinion, it is too early for making definitive statements, which is the most sustainable approach for crop protection. Therefore, we left some ambiguity in the sentence.**

> * "The plant breeding is as old as the domestication ..." This sentence doesn't make sense. You could remove "The" and it would read better.

**[Done]**

> * A more general comment would be to consider spacing out information in paragraphs. The first page is essentially a single paragraph. It may work better if you made a single paragraph introduction to pathogens being an issue and how plant breeding attempts to tackle problems then a second paragraph which states how your approach feeds into this.

**Good point! [Done]**

> * The phrasing of "a combined term
>   that refers to the fields of study in biology ending in -omics," is superfluous. It could simply be "(genomics, proteomics, metabolomics etc.)"

**[Done]**

> * Again, I would consider restructuring. You talk of the breeding for 10k years, jump to omics then back to breeders not using them. It may work better if mentioned how most breeding hasn't evolved since domestication and that your method helps to bring in 21st century technology.

**[Done]**

> * "Introduction ~cing~ of ~the~ so-called".

**[Done]**

> * Overuse of "so-called". Possibly not required at all.

**[Done]**

> * "... significantly withdrawn" I don't think this word means what you want to say. Maybe "arrested" or plainly state "Early phenotyping was held back by the difficulty in developing high-throughput pipelines for both macroscopic and microscopic data".

**Sorry, we probably wanted to write “withhold” or so...It is corrected.**

> * "To contribute to" -> "To solve these problems". Use of "to" twice doesn't read well.

**[Done]**

> * The introduction of your method could be a new paragraph. It would really help the reader jump straight to reading about what you have done. As currently it is hidden amongst background information.

**[Done]**

> * After you introduce your method you jump back to the effects of powdery mildew. As I mentioned previously, this could be part of the introduction and justification of this work.

**[Done]**

> * Figure 1. A more detailed caption is needed. Figures should be independent of article text, so maybe a step by step caption would be useful. Currently I can guess what the figure is saying, but a detailed caption would really help.

**[Done]**

> * Latin names for pathogens should be in italics (typically, not 100% on what JOSS' policy is).

**Yes, sure. Sorry, the formatting was lost during the submission.**

> * When you say "contains modules for" do you mean software modules? If so could you state what the changes are and how difficult would it be to say add another disease for another plant. i.e. if I wanted to do this method for rice plants is it the case of 1 week, 1 month, 1 year? If your method can be applied more widely then it would be to your benefit to state this. Possibly just a sentence on "This method was developed for mildew, with little modification it works with wheat, thus we propose that many other diseases could be applied without difficulty", just an example.

**We mean software modules, though hardware changes might be required as well. We cannot give a clear statement of how much effort will take adding a module for a new disease since the appearance of the disease symptoms and thus the segmentation approach can differ a lot. One day to one year is a pretty realistic interval.**

> * I'd be careful of your conclusion statements. "... Is essential to truly understand the defense mechanism", from reading this text you haven't explicitly stated how your method provides information on defence mechanisms, just that you capture data. Sorry, but this is a subtlety that I feel is important to expand upon in the text. It would give a lot more impact if you clearly state that your method is very useful because X.

**Sorry, the Conclusion part was not meant to be part of the final text. It went there by mistake. It is removed now.** 

> * There are a few spelling and grammar mistakes I haven't pointed out. I think copying and pasting your text into a word-processor (Libre-office or MS-word) and setting to English spellcheck would help a lot.

**Sure, we do it in MS Word plus an additional spelling checker but even this doesn’t help sometimes. We did our best and hopefully, the spelling is better now.**

> * One extra thing I just noticed before hitting comment. I don't see that you've referenced your figure in the text. Maybe it would be helpful to break down also in the text what the steps for this method are i.e. what materials and steps does someone need to do if they wanted to use this method themselves.

**[Done]**

> Again, I do hope you see that these are comments of my opinion and not always correct. I'm still going through the rest of the repository and will have more comments shortly.

**Thank you very much for your efforts!**

**Comment by snowformatics** [comment]
**Dear Nathan. Thank you very much for your critical reading and valuable comments. Your input is
highly appreciated.**

> # Paper Comments
> I'd like to prefix these comments by saying that they are general suggestions that I, as the reader, feel would help improve readability and clarity. If they seem blunt, this is not the intent :)
> 
> * I think a reference to a review article for the first few sentences would be good.

**[Done]**
> * Use of the word 'probably'. Personally I feel this isn't a good word to use when making a scientific point, particularly when not backed up with references.

**We have rephrased the sentence and added references but, in our opinion, it is too early for making definitive statements, which is the most sustainable approach for crop protection. Therefore, we left some ambiguity in the sentence.**

> * "The plant breeding is as old as the domestication ..." This sentence doesn't make sense. You could remove "The" and it would read better.

**[Done]**

> * A more general comment would be to consider spacing out information in paragraphs. The first page is essentially a single paragraph. It may work better if you made a single paragraph introduction to pathogens being an issue and how plant breeding attempts to tackle problems then a second paragraph which states how your approach feeds into this.

**Good point! [Done]**

> * The phrasing of "a combined term
>   that refers to the fields of study in biology ending in -omics," is superfluous. It could simply be "(genomics, proteomics, metabolomics etc.)"

**[Done]**

> * Again, I would consider restructuring. You talk of the breeding for 10k years, jump to omics then back to breeders not using them. It may work better if mentioned how most breeding hasn't evolved since domestication and that your method helps to bring in 21st century technology.

**[Done]**

> * "Introduction ~cing~ of ~the~ so-called".

**[Done]**

> * Overuse of "so-called". Possibly not required at all.

**[Done]**

> * "... significantly withdrawn" I don't think this word means what you want to say. Maybe "arrested" or plainly state "Early phenotyping was held back by the difficulty in developing high-throughput pipelines for both macroscopic and microscopic data".

**Sorry, we probably wanted to write “withhold” or so...It is corrected.**

> * "To contribute to" -> "To solve these problems". Use of "to" twice doesn't read well.

**[Done]**

> * The introduction of your method could be a new paragraph. It would really help the reader jump straight to reading about what you have done. As currently it is hidden amongst background information.

**[Done]**

> * After you introduce your method you jump back to the effects of powdery mildew. As I mentioned previously, this could be part of the introduction and justification of this work.

**[Done]**

> * Figure 1. A more detailed caption is needed. Figures should be independent of article text, so maybe a step by step caption would be useful. Currently I can guess what the figure is saying, but a detailed caption would really help.

**[Done]**

> * Latin names for pathogens should be in italics (typically, not 100% on what JOSS' policy is).

**Yes, sure. Sorry, the formatting was lost during the submission.**

> * When you say "contains modules for" do you mean software modules? If so could you state what the changes are and how difficult would it be to say add another disease for another plant. i.e. if I wanted to do this method for rice plants is it the case of 1 week, 1 month, 1 year? If your method can be applied more widely then it would be to your benefit to state this. Possibly just a sentence on "This method was developed for mildew, with little modification it works with wheat, thus we propose that many other diseases could be applied without difficulty", just an example.

**We mean software modules, though hardware changes might be required as well. We cannot give a clear statement of how much effort will take adding a module for a new disease since the appearance of the disease symptoms and thus the segmentation approach can differ a lot. One day to one year is a pretty realistic interval.**

> * I'd be careful of your conclusion statements. "... Is essential to truly understand the defense mechanism", from reading this text you haven't explicitly stated how your method provides information on defence mechanisms, just that you capture data. Sorry, but this is a subtlety that I feel is important to expand upon in the text. It would give a lot more impact if you clearly state that your method is very useful because X.

**Sorry, the Conclusion part was not meant to be part of the final text. It went there by mistake. It is removed now.** 

> * There are a few spelling and grammar mistakes I haven't pointed out. I think copying and pasting your text into a word-processor (Libre-office or MS-word) and setting to English spellcheck would help a lot.

**Sure, we do it in MS Word plus an additional spelling checker but even this doesn’t help sometimes. We did our best and hopefully, the spelling is better now.**

> * One extra thing I just noticed before hitting comment. I don't see that you've referenced your figure in the text. Maybe it would be helpful to break down also in the text what the steps for this method are i.e. what materials and steps does someone need to do if they wanted to use this method themselves.

**[Done]**

> Again, I do hope you see that these are comments of my opinion and not always correct. I'm still going through the rest of the repository and will have more comments shortly.

**Thank you very much for your efforts!**

**Comment by AoifeHughes** [comment]
I've just had some time to go through the repository. 

I haven't been able to run the tests as it seems dependent on data which is missing (see error below). Is it feasible to possibly include a few images in the repository that would allow potential users to test that the setup works and gives expected results? 

```
(macrobot) ➜  macrobot git:(master) pytest
===================================================================================================================== test session starts ======================================================================================================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
rootdir: /Users/nathanhughes/Git/macrobot
collected 3 items / 1 error / 2 selected

============================================================================================================================ ERRORS ============================================================================================================================
________________________________________________________________________________________________________ ERROR collecting macrobot/tests/test_mildew.py ________________________________________________________________________________________________________
macrobot/tests/test_mildew.py:49: in <module>
    plate_id, numer_of_lanes, final_image_list, file_name = mildew_pipeline()
macrobot/tests/test_mildew.py:17: in mildew_pipeline
    experiments = os.listdir(source_path)
E   FileNotFoundError: [Errno 2] No such file or directory: '/Users/nathanhughes/Git/macrobot/macrobot/data'
=================================================================================================================== short test summary info ====================================================================================================================
ERROR macrobot/tests/test_mildew.py - FileNotFoundError: [Errno 2] No such file or directory: '/Users/nathanhughes/Git/macrobot/macrobot/data'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================================================== 1 error in 16.60s =======================================================================================================================

```

**Comment by snowformatics** [comment]
Hi Nathan,

thanks for the comment. Could you please try the test_image example which is explained here:
https://macrobot.readthedocs.io/en/latest/use_case.html

This should automatically download a test image set. After that it should be possible to run all tests. 

I have to include the download within the tests, thanks for pointing out.

**Comment by AoifeHughes** [comment]
Hi, 

Sorry for the slow responses - I've had a paper deadline myself that's eaten all of my time. 

I've downloaded the dataset from the link you provided. However, it seems that this isn't enough, is there perhaps something specific that needs done? If so this needs streamlined. All tests should be passable from a simple script without modification 

The output from running tests, with the images in the "data" folder.

```
(macrobot) ➜  tests git:(master) ✗ pytest
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nathan/Git/macrobot/macrobot/tests
collected 3 items / 1 error / 2 selected

=================================================================================================================================== ERRORS ===================================================================================================================================
______________________________________________________________________________________________________________________ ERROR collecting test_mildew.py _______________________________________________________________________________________________________________________
test_mildew.py:49: in <module>
    plate_id, numer_of_lanes, final_image_list, file_name = mildew_pipeline()
test_mildew.py:45: in mildew_pipeline
    return plate_id, numer_of_lanes, final_image_list, file_name
E   UnboundLocalError: local variable 'plate_id' referenced before assignment
------------------------------------------------------------------------------------------------------------------------------ Captured stdout -------------------------------------------------------------------------------------------------------------------------------

=== Start Macrobot pipeline ===
 Experiment: Image test set for Macrobot software validation
Skip /Users/nathan/Git/macrobot/macrobot/dataImage test set for Macrobot software validation because it is not a directory.

=== End Macrobot pipeline ===
========================================================================================================================== short test summary info ===========================================================================================================================
ERROR test_mildew.py - UnboundLocalError: local variable 'plate_id' referenced before assignment
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================================================== 1 error in 0.58s ==============================================================================================================================
```


I've also tried running the command-line app and I get this: 


```
(macrobot) ➜  macrobot git:(master) ✗ mb -s data/ -d results/ -p mildew
/Users/nathan/opt/anaconda3/envs/macrobot/lib/python3.8/site-packages/macrobot/data
/Users/nathan/opt/anaconda3/envs/macrobot/lib/python3.8/site-packages/macrobot/data
data/
Namespace(destination_path='results/', procedure='mildew', source_path='data/') <class 'macrobot.bgt.BgtSegmenter'>

=== Start Macrobot pipeline ===
 Experiment: gb2_exp40
Skip data/gb2_exp40 because it is not a valid directory.

=== End Macrobot pipeline ===
Skip data/.DS_Store because it is not a valid directory.

=== End Macrobot pipeline ===
```

This is the file structure I've used: [https://i.imgur.com/DfPLN53.png](https://i.imgur.com/DfPLN53.png)

**Comment by snowformatics** [comment]
Hi Nathan,

no problem, I think we are all very busy at the moment..

Thanks for testing again, the folder structure looks correct. Both error messages show that the software has problem with the folder structure. I tried to use os.join() to deal with the file paths but I have no experience how it will work on Linux or Mac. I developed and tried the software only on Windows because our institution and our users supports / use only Windows OS (sorry about that). Would it be possible to try the software on a Windows system? Or maybe the other reviewers could test on Windows? 

I am sorry about your inconvenience but as mentioned in the paper, the target of the software is Windows OS.

Best regards
Stefanie

**Comment by snowformatics** [comment]
On last try, could you start the command-line app with the full paths please? 

So instead of:
mb -s data/ -d results/ -p mildew

This (with linux path):
mb -s C:\Users\xy\Desktop\data\ -d C:\Users\xy\Desktop\results\ -p mildew

Thanks
