### ISSUE TITLE
JOSS Review 

### ISSUE THREAD

**Issue by jizecn** [snowformatics/macrobot#4]
Dear authors, 

I have just done the review and installed the software on my computer following the suggestion. I can also prove it works on Linux too (using Anaconda, in addition to Windows as described).  
The only minor issue is the test program (link https://macrobot.readthedocs.io/en/latest/use_case.html) 
% mb -s test_images -d ~/Desktop/mb_results -p mildew

- Can you provide an example to demonstrate how to run with the new images downloaded from the link provided? I tried with different options of -s specifying the source directory, but could not make it work. It always returns "....... it is not a valid directory."
- In addition to the above, it creates several sub-folders even it is not successfully executed. Maybe the sub-folders could be cleaned if unsuccessful? 
- For installation, please specifying the version of Python more specifically. I tried with my other Python 3.6 environment, and it could not find the package. It worked with Python 3.8 (the recent default one).

**Comment by snowformatics** [comment]
Dear jizecn, thank you very much for your feedback and time,

I uploaded the test image set again. Please download, unzip and use the data folder with the -s option. I will provide a better manual for using the test images. I am happy that you successfully installed the software on Linux.

Download link:
https://zenodo.org/record/3904105/files/data.zip?download=1

In addition I will specify the Python version, thanks for pointing out!

Best regards
Stefanie

> Dear authors,
> 
> I have just done the review and installed the software on my computer following the suggestion. I can also prove it works on Linux too (using Anaconda, in addition to Windows as described).
> The only minor issue is the test program (link https://macrobot.readthedocs.io/en/latest/use_case.html)
> % mb -s test_images -d ~/Desktop/mb_results -p mildew
> 
> * Can you provide an example to demonstrate how to run with the new images downloaded from the link provided? I tried with different options of -s specifying the source directory, but could not make it work. It always returns "....... it is not a valid directory."
> * In addition to the above, it creates several sub-folders even it is not successfully executed. Maybe the sub-folders could be cleaned if unsuccessful?
> * For installation, please specifying the version of Python more specifically. I tried with my other Python 3.6 environment, and it could not find the package. It worked with Python 3.8 (the recent default one).

**Comment by snowformatics** [comment]
Closed paper was published
