### ISSUE TITLE
[JOSS] Community guidelines suggestions

### ISSUE THREAD

**Issue by phckopper** [snowformatics/macrobot#6]
Dear authors,

For the Contributions page of your wiki, I'd like to suggest you to:

- Provide additional info to third-parties who wish to contribute, such as how is the repository organized, how to submit a pull request (providing a template is usually nice, but not required), etc
- Provide an example of how a bug report should look like, what information is needed, etc
- Provide a contact point for users needing support or ask them to use GitHub Issues.

And keep the roadmap, it is great to have your needs clearly stated! Nice job with that!

This suggestion is made in regard to the [Community Guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) review criteria.

**Comment by snowformatics** [comment]
Hi,

thank you very much for your input. I opened some issues with label "help wanted" and "good first issue" and updated the wiki page with some more information and guidance.

Hopefully this lead to some contributions...

**Comment by phckopper** [comment]
Great! Nicely done! I'll now close this issue as that matter has been resolved.
